# Generated by Django 4.1.2 on 2022-11-05 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeID',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('BatchNo', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('BatchNo', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('TraineeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('BatchNo', models.CharField(max_length=15)),
                ('ContactNo', models.CharField(max_length=15)),
                ('ContactAddress', models.CharField(max_length=100)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('DueAmount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'db_table': 'Trainee',
            },
        ),
    ]
